dist: bionic
language: php
php:
  - 7.2
  - 7.3

branch:
  only:
    - master

services:
  - mysql

install:
  - cp .env.travis .env
  - sudo mysql -e 'create database homestead;'
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

cache:
  directories:
    - node_modules
    - "$HOME/.composer/cache/files"
    - vendor

before_deploy:
  - rm .env
  - cp .env.example .env
  - php artisan key:generate

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "h3vLL7r3wp4OE40aGpd0yTekP0SHCmg2iF3Vjz5SfnS7e0BjxCTikJ8yTf+bJHvyxuyZrsE0ytdvo7Df9JbFpqaVmCRMevHZ31sLVJS3toFFSj5GEmgZ+RUJda2nR+fB8qp5ab8y6u3wBdI0KhEGU1HP8pSVgggfmqH3+gDCc94kjtm6N6ur48VUhwIelPwzUMc5sDg8T+x9V4H5OPtIhKoCZVcGlU10J1d9w39b5hI2ErQunVzXNwk1jL0qBqdMzHt5Qt9pcnC0oZkz4PWJ/hSa4s933ywKZjJCGj9+Lz5lVLS5xCyYsRKT7zwW4ZEa/K6iXccbOCcqACoedyxVz2ij/crbg5WBrMm5CIEJp6HHTvnQV7KQvBthk5vIVoPjBivVMzx/kcTZoFP4wAIpzdhnckS8uOBqfi1gimAqnOz5A8RL/+D1JuvbF2Luyl5V/a1j87g2/JocggxYAiPKvBdBTSfLMabhvg0KOTTPupQzhTnPJa9L+w7bP9/bV8urPqFqXlLR95VsfjKa9fSm0VbL4WUXnRCI1IRgR4Sm70URrQkLQSeXxxyyQIWPKavIKPEeYVsRFR2ARV2OHBCRCWM0irWjfhZQjykdpTI2wyzqtZV6fbXibTakAEtTx5e2fPgXfY1W6B9AdTeNgS03FV/Z1mI0F3LgJzW4TQCaj8A="
  secret_access_key:
    secure: "OChMzDvcHjo5UrbDapdzbLl2v6Srt8DJ3hgamrgjaro3aURQAiY5Y7RvXKW1I9RycVEKqoUc0SN5cTGN/uqFzOjwjYXUd9TY3mg9AXCq9GgU1X0GA+5w3i4s4UuvXkn2vxC4BNn30mkXib6ReqNuaTnIQsy2p6Qro73tozSta7Clh2RlE0wHOF2f97uG94JQrn+r5J1fmdXuEnkE9GCYHAuntkcA00cApDcngxRsHixgzpMR1qYIZurCVHjOsLruolcMiXRLK4JVaPnRJ64SHZD1q5LGepRPA8YCMj1OKR2WG7UewaDp2LCFZ7MQvHeEpU6ngLw7lKxbK+pO9eurwvhqmgzl19/VvxxsOauyGiJyjEeGfMgCL+VCuq7EPPNmhjpdk6EUfSXEgvei6CQ6LlkEfdiNa8rlrezpbORk0Bv3YxxsKM1kQRiYUcmqyeIvM9lff+Cd1mJiavr0SymC+qNq75QBbLseu8kWVAqeCer3Mozg0NrI+GoeFn5kE4SoVVLollH+smQc4pC8FBT811RtFLBELwUK21uEJnwZjWU0O5hDBMdUSgPGkMbcw0yvYBCKSv7bfSbgnVM1DUC6eotAJlNgvGwREWrwl5p62v1IEjNEOfozfxZfqoha9pIA9TJrGqpnpmcY2DGb6jGZ0DaE8vkPJRu/EKhQYZhKO4g="
  region: "us-west-2"
  app: "GamificationApplication"
  env: "Gamificationapplication-env"
  bucket_name: "elasticbeanstalk-us-west-2-514451421785"
  skip_cleanup: true

after_deploy:
  - echo "done deploying"
