dist: bionic
language: php
php:
  - 7.2
  - 7.3

branch:
  only:
    - master

services:
  - mysql

install:
  - cp .env.travis .env
  - sudo mysql -e 'create database homestead;'
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

cache:
  directories:
    - node_modules
    - "$HOME/.composer/cache/files"
    - vendor
