dist: bionic
language: php
php:
  - 7.2
  - 7.3

services:
  - mysql

addons:
  chrome: stable

install:
  - cp .env.travis .env
  - sudo mysql -e 'create database homestead;'
  # - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate
  - php artisan dusk:chrome-driver

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk

cache:
  directories:
    - node_modules
    - "$HOME/.composer/cache/files"
    - vendor
